tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'ni22215.central-india.azure'
      user: 'PURUSHOTHAMAN'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: dev
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: 'ni22215.central-india.azure'
      user: 'not needed'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh